### ISSUE TITLE
Zwei Dockerfiles

### ISSUE THREAD

**Issue by dominikbraun** [dev-community-de/code-formatter#10]
Ich habe meine letzten Änderungen im Dockerfile unter `.docker`-Verzeichnis durchgeführt, das auch in der `docker-compose.yml` verwendet wird.

Wird dann das [Dockerfile im Root](https://github.com/dev-community-de/code-formatter/blob/master/Dockerfile) überhaupt noch benötigt?

**Comment by jr-cologne** [comment]
Ja, das wird noch benötigt. Ich habe allerdings zwischenzeitlich selbst auch vergessen, dass es das Dockerfile noch gibt.

Kurz zur Erklärung:
Das Dockerfile im Root-Verzeichnis ist für die Produktionsumgebung.
Gilt genauso für vhost.conf im Root-Verzeichnis.
Die wesentliche Unterschied ist natürlich der Port, der exposed wird.
Zusätzlich wird aber auch noch die PHP-Konfigurationsdatei für production kopiert und somit aktiviert.

Sind also kleine Unterschiede zwischen Dev-Umgebung und Produktion, weswegen ich leider diese Dopplung einführen musste.

Würdest du noch das Dockerfile im Root-Verzeichnis entsprechend deiner Änderungen aktualisieren, damit ich das Ganze dann auch gefahrlos deployen kann?
Oder hast du eine bessere Idee, wie man das vielleicht sogar mit einem einzigen Dockerfile regeln kann?
Zu beachten ist im Grunde der Deployment-Prozess, der in der Datei cloudbuild.yaml angegeben ist.
Man kann doch Docker sicher auch Variablen o.ä. übergeben, wonach man dann zwischen verschiedenen Umgebungen unterscheiden kann, oder?
Na ja, erstmal ins Bett...

Edit:
Ich habe es jetzt erstmal beim Alten belassen und entsprechend nur das Production-Dockerfile aktualisiert.

**Comment by dominikbraun** [comment]
> Oder hast du eine bessere Idee, wie man das vielleicht sogar mit einem einzigen Dockerfile regeln kann?

Wenn die Dockerfiles mal zu groß/unübersichtlich werden, kann man die Dopplungen umgehen, vorerst würde ich es mal der Einfachheit halber so lassen.
