### ISSUE TITLE
Unclosed CODE-BBCode (invalid syntax) gets corrected by the parser

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#28]
I don't know if this is a real issue, but the outcome can be a bit surprising:

IF you pass this code to the formatter:
`[CODE]opened but never closed`

The expected result should be some kind of error, but instead, the result looks like this:
```
[CODE lang="text"]opened but never closed
[/CODE]
```

@jr-cologne what do you think? should we discard/report invalid bbcodes or silently accept and correct them (current behavior)?

**Comment by wookiefriseur** [comment]
I could see this happening if someone is trying to write a codeblock by hand and mistypes the closing tag or copies lines after the block has been generated.

I would expect it not to display a code block at all, but BBCode is a bit like HTML in that regard. It tries to do the best it can with what it gets.

Therefore I think closing broken Tags is fine.

**Comment by jr-cologne** [comment]
I guess this is fine as well. Let's keep it like that for now.
