### ISSUE TITLE
Nested CODE-BBCodes produce wrong result

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#29]
Nested CODE-BBCodes are not supported, but the current behavior differs from XenForo:

Input:
`[CODE][CODE]test[/CODE][/CODE]`

Expected result (not sure):
`[CODE lang="text"][CODE lang="text"]test[/CODE][/CODE]`

@jr-cologne what do you think should be the "expected result" in this case?

Actual result:
`[CODE lang="text"][/CODE][CODE lang="text"][/CODE]`

Nesting gets wrongly corrected and the text-content gets discarded.

**Comment by wookiefriseur** [comment]
Is that a Xenforo bug as well? My human parsing machine is telling me the result should be `[CODE lang="text"][CODE]test[/CODE][/CODE]`. I think they're using regex matching in the backend and I can understand that they wouldn't want to do expensive nest matching.

Whatever we do with that, the text content has to be saved. Easiest fix would probably be to ignore it if it is nested (if it contains any more `[CODE`). Alternative would be to discard outer layers, but they could be containing text as well (if someone clicked in the wrong spot to insert a new codeblock).

**Comment by asccc** [comment]
Yeah, i was thinking the same. XenForo probably just matches the closest [/CODE] and ignores the second [CODE] inside.
The result looks like this:
![grafik](https://user-images.githubusercontent.com/42143765/87150791-09594000-c2b3-11ea-8839-e578b52b4914.png)
https://dev-community.de/threads/php-cf-fixer-integration-tests.150/#post-970

**Comment by jr-cologne** [comment]
I don't think this is a XenForo issue as well. Don't forget that we are still using v0.3.0-alpha in production. Everything you post in the forum is therefore going through our potentially buggy code-formatter.

I will check which behavior a plain XenForo installation has.

Since people might want to showcase their BB codes, I would also say this is the expected result:
```
[CODE lang="text"][CODE lang="text"]test[/CODE][/CODE]
```

An alternative would be without the `lang` attribute as this might cause bugs in XenForo because there is no language called `text`.

**Comment by asccc** [comment]
I just created a demo installation and checked it. 
The behavior is the same:
![grafik](https://user-images.githubusercontent.com/42143765/87236839-483fe080-c3ee-11ea-9f29-b494e132ec52.png)

**Comment by jr-cologne** [comment]
Ok, interesting.
But how did you manage to set up a demo installation? 😄

**Comment by asccc** [comment]
You can setup a free demo at https://xenforo.com/

**Comment by jr-cologne** [comment]
Oh, ok. That's a nice thing for quick testing.

On my local PC, I have set up a Docker environment for XenForo. If I want to test anything, I always have to find the project directory with the XenForo installation, spin up Docker and only then I can test things.
If there's a new version of XenForo, I have to manually download the code and install everything from scratch or update the necessary files.
It's a bit cumbersome, but this is the only way to properly develop add-ons and stuff. :smiley: 

So, I was wondering how you got access to the XenForo code/installation without being a license holder. :sweat_smile:
