### ISSUE TITLE
Add support for PLAIN-BBCode

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#30]
XenForo supports a PLAIN-BBCode to disable BBCode-parsing.

Input:
`[PLAIN][CODE=css].test{color:red;}[/CODE][/PLAIN]`

Expected result:
`[PLAIN][CODE=css].test{color:red;}[/CODE][/PLAIN]` (no change)

Actual result:
```
[PLAIN][CODE lang="css"].test {
    color: red;
}
[/CODE][/PLAIN]
```

**Comment by wookiefriseur** [comment]
Hmm.. this might be something we should not send to the formatter at all. 

Maybe the check should happen here: https://github.com/dev-community-de/dev-community-code-formatter-xenforo-addon/blob/c165f9a9b2e4018d6b12ef5a81b46d64c6307f84/DevCommunityDE/CodeFormatter/CodeFormatter.php#L70

Edit: My reasoning behind this is, that it's technically not even a code block. 
But we would have to account for mixed blocks (plain + normal codeblocks in the same post).

**Comment by jr-cologne** [comment]
I agree with @wookiefriseur.
The [PLAIN] BB code could then be also used to show the actual formatting of your code / prevent code blocks from being formatted or displayed as code blocks.
So, I would maybe prefer dealing with this on the add-on level, too.
