### ISSUE TITLE
Parser should not transform CODE-BBCode arguments

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#32]
Currently the parser transforms arguments to a formal notation, but i think the parser should emit them as-is.

-------

Input:
`[CODE=css].test { color: red; }[/CODE]`

Expected result:
```
[CODE=css].test {
    color: red;
}
[/CODE]
```

Actual result:
```
[CODE lang="css"].test {
    color: red;
}
[/CODE]
```

-------

Input:
`[CODE]test[/CODE]`

Expected result:
```
[CODE]test[/CODE]
```

Actual result:
```
[CODE lang="text"]test[/CODE]
```

**Comment by jr-cologne** [comment]
Yep, I think this is something you introduced with the new parser.

Our XenForo Code block add-on expects a title argument if a code block is formatted this way.
I believe I've already seen errors in the forum which had to do with the missing title argument.
