### ISSUE TITLE
Use prettier as daemon to speed-up formatting

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#38]
I noticed that prettier is pretty slow compared to other formatters and i was wondering if we can speed things up a bit if we use a daemon to keep prettier in its JIT'ed state across requests.

To achieve this, i wrote a little script to spin-up a server which loads prettier and reuses it for incoming requests.

Here is the simple script: 
https://github.com/asccc/code-formatter/blob/even-prettier/prettierd.js

The benchmark-script i used:
https://gist.github.com/asccc/71101f42269e2acbcfd09059d42a39f5

Here are some numbers:
```
prettier (npx)       0.357160
prettier (bin)       0.341608
prettier (daemon)    0.104197
```

The speed-up is quite impressive if you ask me.
What do you think?

ping @wookiefriseur

**Comment by wookiefriseur** [comment]
Uhh, nice. I had "look for a way to make a binary from js" on my todo list 😄 . But it looks like the daemon solution gets it down to acceptable speeds already. Good job! 👍

**Comment by asccc** [comment]
I have no idea how to integrate this service in docker ...
Is there a way to install and start systemd services in docker?! It runs fine on my system without docker ...

**Comment by wookiefriseur** [comment]
It seems this image does not have systemd, which would require some ugly low level script for init instead of the pretty `prettierd.service` (we'd have to copy it and then use `update-rc.d` to let it create symlinks in`/etc/rc*.d` and set run levels and so on).

But it looks like `start-stop-daemon` could be used instead.

Trying right now with:
`start-stop-daemon --group www-data --exec /srv/app/prettierd.js --start --background --chdir /srv/app --retry 0/0 --verbose`

I don't understand the retry syntax 100% yet.. it takes a timeout or a schedule, I think 0/0 should be an endless schedule loop.


That seems to be one way of getting it to run, though it does not run for me yet. I also have a problem with npm not creating `node_modules`.. so that might be the reason why I'm getting this error:
```bash
root@3a4352899c7b:/srv/app# start-stop-daemon --group www-data --exec /srv/app/prettierd.js --start --chdir /srv/app --retry 0/0 --verbose
Starting /srv/app/prettierd.js...
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'prettier'
Require stack:
- /srv/app/prettierd.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/srv/app/prettierd.js:35:18)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/srv/app/prettierd.js' ]
}
```

Another way would be to install systemd, and I tried that manually but I don't know how to get it to take over the services.

**Comment by asccc** [comment]
Did you execute `npm install` before launching the  daemon?

**Comment by wookiefriseur** [comment]
Yeah, the whole `docker-compose.exe up -d --build --force-recreate` which executes the docker file in the web folder. I let it output `pwd` and `ls` before starting the prettier service and it was always empty except for a package-lock.json, as if it was not mounted yet at that point. That's why I even changed the docker file to copy the necessary files first:

```dockerfile
FROM php:7.4-apache

COPY .docker/web/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY package.json /srv/app/package.json
COPY package-lock.json /srv/app/package-lock.json
COPY prettierd.js /srv/app/prettierd.js

WORKDIR /srv/app

# Packages for formatting C and C++ code
RUN apt-get update -y && \
    apt-get install -y clang-format

# Packages for formatting Go code
RUN apt-get update -y && \
    apt-get install -y golang

# Packages for formatting Python code
RUN apt-get update -y && \
    apt-get install -y python3.7-minimal python3-pip && \
    pip3 install black

# Packages for formatting code using Prettier (JS, CSS, etc)
RUN apt-get update -y && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && npm install

# Install prettier-daemon
#RUN start-stop-daemon --start --exec /srv/app/prettierd.js
``` 

But it's probably just some read/write permission problem with Docker Desktop .. selfmade Windows problems 😆 
Will check it later in a Linux VM.

**Comment by asccc** [comment]
There is no `npm install` in there, you have to execute `npm install` before you build the container (at least that's what i was doing the whole time) same for `composer install`.

**Comment by asccc** [comment]
// Forget what i was saying, `npm install` is there

**Comment by wookiefriseur** [comment]
Edit: yeah, it's in the dockerfile

When doing it by hand, the daemon starts:
`root       133  8.2  0.2 588188 42452 ?        Sl   20:47   0:00 node /srv/app/prettierd.js` (guess switching to group www-data is not enough, also have to switch the user)

This seems to work:
`start-stop-daemon --group www-data --user www-data --exec /srv/app/prettierd.js --chdir /srv/app --retry 0/0 --verbose --start --background`

Edit: woops..still root.. have to look at the man page again 😟  .. if the --user and --group switches does not want to work, a `su` might do...

But at least that command line parameter is 1 way to get it to start as a daemon. It's just not very pretty.

**Comment by asccc** [comment]
We could create a second container for this tiny script and expose its port to the code-formatter container.
I'm just guessing here, but that's the docker way i guess (containers, containers everywhere). 

Little overkill if you ask me and i don't know if this is worth the trouble...

**Comment by jr-cologne** [comment]
Nice performance improvements. 😃 👍 

If we could get the daemon thingy to properly work inside the same container, it would be great and way better than creating and exposing a separate container.
I don't really want to mess around with networking stuff in Google Cloud. 😅

**Comment by wookiefriseur** [comment]
This one starts it as the correct user and group and seems to work so far..  but I'm not sure if it restarts on crash:

`start-stop-daemon --group www-data --chuid www-data --exec /srv/app/prettierd.js --chdir /srv/app --retry 0/0 --verbose --start --background` 

ps -aux: `www-data   252 12.5  0.2 585732 39844 ?        Sl   21:17   0:00 node /srv/app/prettierd.js`

**Edit: Ok, `--retry` is only used when stopping it. This daemon does not autorestart itself as it is right now.**

**Comment by asccc** [comment]
Can you post your Dockerfile?

**Comment by wookiefriseur** [comment]
This only works after I manually do `npm install` and then execute the start-stop-daemon command:

```Dockerfile
FROM php:7.4-apache

COPY .docker/web/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY package.json /srv/app/package.json
COPY package-lock.json /srv/app/package-lock.json
COPY prettierd.js /srv/app/prettierd.js

WORKDIR /srv/app

# Packages for formatting C and C++ code
RUN apt-get update -y && \
    apt-get install -y clang-format

# Packages for formatting Go code
RUN apt-get update -y && \
    apt-get install -y golang

# Packages for formatting Python code
RUN apt-get update -y && \
    apt-get install -y python3.7-minimal python3-pip && \
    pip3 install black

# Packages for formatting code using Prettier (JS, CSS, etc)
RUN apt-get update -y && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && npm install

# Install prettier-daemon
RUN start-stop-daemon               \
    --group www-data                \
    --chuid www-data                \
    --chdir /srv/app                \
    --exec /srv/app/prettierd.js    \
    --start                         \
    --background
```

I'm looking right now at some examples for init.d-files, So far I only saw people using while true loops to restart the service if crashed .. might be the way to go if we start it without `--background` but run the loop in the background 😃

**Comment by asccc** [comment]
Hmm, `docker build` accepts it, but the process is not running after `docker run`.
I'm on Ubuntu.

**Comment by asccc** [comment]
I think i have a working solution now. I just created a custom entrypoint for the image:

```
#!/usr/bin/env sh
/srv/app/prettierd.js &
apache2-foreground
```

This will start the daemon and then run apache in foreground.
We can replace the direct launch (`/srv/app/prettierd.js &`) with a custom script (the while true approach) and use start-stop-daemon there.

**Comment by wookiefriseur** [comment]
Yeah, docker seems to despawn temporary container instances, with all their processes. So it was started but then killed again.

Other way would have been to start the daemon on demand, if it's not running already. But that would be slower than a blocking loop.
