### ISSUE TITLE
gofmt and python/black (and probably prettier-php) error out on invalid syntax

### ISSUE THREAD

**Issue by asccc** [dev-community-de/code-formatter#40]
A syntax error currently discards code entirely, which means that a empty code-tag (or just an error message) gets sent back to the forum (= the code [even if invalid] is lost).

We should definitively address this issue before the next release! 
My suggestions would be to handle exceptions during the formatting and use the original (unformatted) code as fallback.

Original:
https://github.com/dev-community-de/code-formatter/blob/master/app/CodeFormatterApp.php#L90

```php
$nodeBody = $node->getBody();
\assert(\is_string($nodeBody));
$result = $formatter->exec($nodeBody);
return $this->exportNode($node, $result);
```

Fallback:
```php
$nodeBody = $node->getBody();
\assert(\is_string($nodeBody));

try {
  $result = $formatter->exec($nodeBody);
  return $this->exportNode($node, $result);
} catch (Exception $err) {
  // null => use original code-body
  return $this->exportNode($node, null);
}
```

**Comment by asccc** [comment]
@jr-cologne maybe you can sneak this change in during the implementation of https://github.com/dev-community-de/code-formatter/pull/26 😃

**Comment by asccc** [comment]
The current production-code had this working already as a side-effect:
https://github.com/dev-community-de/code-formatter/blob/v0.3.0-alpha/app/CodeFormatterApp.php#L77

**Comment by jr-cologne** [comment]
Yeah, this issue definitely has to be fixed.
Thanks for calling that out.
I will take care of it.
